[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@astrojs/netlify"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200 